### ISSUE TITLE
Error in git bash 

### ISSUE THREAD

**Issue by GingerTe** [Greewil/version-update-helper#14]
**Describe the bug**
Incorrect work in windows git bash

**To Reproduce**
1. Run `vuh uv -pm=BACKEND`
2. See error
`getting main version
fatal: ambiguous argument 'origin\main;.vuh': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
(vuh : ERROR) Failed to read remote configuration file origin/main:.vuh!
(vuh : WARNING) vuh will use local configuration to get remote version from origin/main
origin/main: 0.4.1
`

Alert happend on line
`git show origin/main:.vuh` 

`fatal: ambiguous argument 'origin\main;.vuh': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
`

Git bash `git show`can't work properly with files started with dot

**Desktop (please complete the following information):**
 - Windows 11
 - git version 2.45.1.windows.1 [Git Bash]
 - Vuh version 2.2.0

**Comment by Greewil** [comment]
Fixed in 2.5.3 (https://github.com/Greewil/version-update-helper/releases/tag/v2.5.3)

Seems like it's really problem with `git show` in gitbash (somewhere there https://github.com/git-for-windows). It automatically converts ':.' construction to ';.'.
So I changed getting main version mechanism in vuh. Now it will clone repo to /tmp dir to get all needed files from origin/main.
